# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jwx < Formula
  desc "A beautiful CLI for working with JSON Web Tokens"
  homepage "https://github.com/manimovassagh/jwx"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/manimovassagh/jwx/releases/download/v1.2.2/jwx_1.2.2_darwin_amd64.tar.gz"
      sha256 "a3b0b138de54e1d18b3fc3cccb2c3efb68afc48d399379ec568e4a8731cbcac6"

      define_method(:install) do
        bin.install "jwx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/manimovassagh/jwx/releases/download/v1.2.2/jwx_1.2.2_darwin_arm64.tar.gz"
      sha256 "df7f46fe585646f6d997c1f05498da6d84475b3c6878979e0b3520241b283f2c"

      define_method(:install) do
        bin.install "jwx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/manimovassagh/jwx/releases/download/v1.2.2/jwx_1.2.2_linux_amd64.tar.gz"
      sha256 "4e084a861271eb5b527f983e18aa863e421b4522d925d0eced68007506a87827"
      define_method(:install) do
        bin.install "jwx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manimovassagh/jwx/releases/download/v1.2.2/jwx_1.2.2_linux_arm64.tar.gz"
      sha256 "8088e34d4157ed7702d3f3caef08ef393ca459bad22297f71a582e31abb468f4"
      define_method(:install) do
        bin.install "jwx"
      end
    end
  end

  test do
    system bin/"jwx", "version"
  end
end
